fix typings
vtex-sites/storecomponents.store pull request #1005
Opened 2021-06-29 20:51 UTC by tlgimenes

## What's the purpose of this PR?
Moves product page query to this repo. More info at: https://github.com/vtex/faststore/pull/795

## How to test it?
Enter in the pdps. Nothing should have changed

2021-06-30 16:57 UTC, igorbrasileiro requested changes
Left some request changes

2021-06-30 16:57 UTC, igorbrasileiro commented on src/@vtex/gatsby-theme-store/views/product/AboveTheFold.tsx
> +const AboveTheFold: FC<ProductViewProps> = ({ product, slug }: any) => {
Fix type any. It has product and slug at least.

2021-06-30 16:57 UTC, igorbrasileiro commented on src/@vtex/gatsby-theme-store/views/product/SEO/useMetadata.tsx
> +  const { product }: any = options
Why this type is any, maybe we need to fix it.

2021-06-30 22:16 UTC, tlgimenes commented on src/@vtex/gatsby-theme-store/views/product/SEO/useMetadata.tsx
> +  const { product }: any = options
I'm doing another pr to fix this once & all. However, let's leave it like this for now since all typings are wrong

2021-07-01 19:41 UTC, igorbrasileiro approved these changes

2021-07-01 19:42 UTC, merged