Banner for search terms
vtex-sites/storecomponents.store pull request #1006
Opened 2021-07-01 16:47 UTC by igorbrasileiro

## What's the purpose of this pull request?
Add search banners related to the search term of the user. So if the user searches the term `foo`  and exists a rule that has a banner for `foo` term, the search page will show a banner

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em> 

## References
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>  

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

2021-07-01 17:02 UTC, igorbrasileiro commented on src/@vtex/gatsby-plugin-theme-ui/searchBanner.ts
> +          height: '233px',
maxHeight

2021-07-01 20:46 UTC, tlgimenes commented on src/components/search/Banner.tsx
> +      sx={{ variant: 'search.banner.container' }}
why not moving the styles here? take a look here for more inspiration
https://github.com/vtex-sites/btglobal.store/pull/616

2021-07-01 20:48 UTC, igorbrasileiro commented on src/components/search/Banner.tsx
> +      sx={{ variant: 'search.banner.container' }}
Sure.

2021-07-01 21:37 UTC, tlgimenes commented
Nice! Do you have any banner/search term for us to test it? thanks!

2021-07-02 12:45 UTC, igorbrasileiro commented
> Nice! Do you have any banner/search term for us to test it? thanks!

Sure, search `ten`

2021-07-02 14:22 UTC, tlgimenes requested changes

2021-07-02 14:22 UTC, tlgimenes commented on src/components/search/Banner.tsx
> +      dangerouslySetInnerHTML={{ __html: banner.html }}
Hmmm, I don't know. I have mixed feelings about this. First issue in here is that there is a layout shift in the banner. Second issue I see in here is that the resize/params for the banner are comming from IS, and we are not using the <Image /> component from gatsby-plugin-image. This may easily break if we change the images.conf.js file for something else. Also, the image is pretty big, with 94Kb

2021-07-05 13:45 UTC, igorbrasileiro commented on src/components/search/Banner.tsx
> +      dangerouslySetInnerHTML={{ __html: banner.html }}
We don't have access directly to the imagem, the image received is inside an html stringified

2021-07-05 14:21 UTC, igorbrasileiro commented on src/components/search/Banner.tsx
> +      dangerouslySetInnerHTML={{ __html: banner.html }}
Can you describe how do you realized this layout shift?

2021-07-05 16:26 UTC, tlgimenes commented on src/components/search/styles.json
> +      "maxHeight": "233px",
why not using just height?

2021-07-05 16:29 UTC, tlgimenes requested changes
We are still using the unsafe `thumbor` url. If somehow we change [this breakpoint](https://github.com/vtex-sites/storecomponents.store/blob/cefffca6be42a26cf23c82ddf4a0610c48c21e26/src/images.config.js#L5) this feature will silently stop working

![image](https://user-images.githubusercontent.com/1753396/124499749-ea41a100-dd94-11eb-8791-c31a8df0fcbe.png)

2021-07-05 18:37 UTC, igorbrasileiro commented on src/components/search/styles.json
> +      "maxHeight": "233px",
Sure

2021-07-05 18:39 UTC, tlgimenes approved these changes

2021-07-05 18:40 UTC, merged