Feat/cypress order.tests
vtex-sites/storecomponents.store pull request #1022
Opened 2021-07-12 20:17 UTC by bentoper

## What's the purpose of this pull request?
Adds e2e tests related to product orders.

## How it works? 
Tests for broken links.

## How to test it?
Using either a production or a dev build just run `yarn cy:open` and run the desired files or `yarn cy:run` to run all tests on the CLI. In either case the `baseUrl` on `cypress.json` should be the path to where the store is running.

2021-08-17 01:53 UTC, Gmantiqueira commented on cypress/e2e/order/orders.test.js
> +    cy.get('[data-testid="goCheckout"').should('be.enabled').click()
Why not using `cy.getById` instead of `cy.get`?

2021-08-17 01:53 UTC, Gmantiqueira commented on cypress/e2e/order/orders.test.js
> +    cy.get('[class="product-name"').should('include.text', 'Tank White')
Typo here, fix to `[class="product-name"]'` instead of `[class="product-name"'`.

By the way you can use `cy.get(".product-name")`.

2021-08-17 01:53 UTC, Gmantiqueira commented on cypress/e2e/order/orders.test.js
> +    cy.get('[data-testid="numericStepperPlus"]').eq(1).click()
`getById` instead of `get`

2021-08-17 01:53 UTC, Gmantiqueira commented on cypress/e2e/order/orders.test.js
> +    cy.get('[data-testid="goCheckout"').should('be.enabled').click()
Typo, but `getById` instead of `get`

2021-08-17 13:21 UTC, igorbrasileiro requested changes

2021-08-17 13:21 UTC, igorbrasileiro commented on cypress/e2e/order/orders.test.js
> +    cy.get('[data-testid="goCheckout"').should('be.enabled').click()
A typo here 
```suggestion
    cy.get('[data-testid="goCheckout"]').should('be.enabled').click()
```

2021-08-30 19:49 UTC, bentoper commented on cypress/e2e/order/orders.test.js
> +    cy.get('[data-testid="numericStepperPlus"]').eq(1).click()
As of right now test-tools `clickById` isn't working with index, gonna open a PR to fix it.

2021-09-10 15:00 UTC, emersonlaurentino approved these changes

2021-09-10 15:01 UTC, merged