Use google tag manager plugin
vtex-sites/storecomponents.store pull request #444
Opened 2021-01-20 01:05 UTC by gris

## What's the purpose of this pull request?
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>
To use the new google tag manager plugin

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em> 
See that the script is being loaded into the webpage.

## References
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>  

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

2021-01-20 16:31 UTC, klzns approved these changes

2021-01-20 16:31 UTC, klzns commented on gatsby-browser.js
> +// noop
Maybe remove this file?

2021-01-20 17:02 UTC, gris commented on gatsby-browser.js
> +// noop
Done!

2021-01-21 18:32 UTC, tlgimenes commented
Please remove this repo's gatsby-browser.js

2021-01-21 18:32 UTC, tlgimenes requested changes
Please remove this repo's gatsby-browser.js

2021-01-21 18:36 UTC, gris commented
It was already removed @tlgimenes

2021-01-21 20:04 UTC, tlgimenes approved these changes

2021-01-21 20:05 UTC, merged