Create CMS preview route for homepage content type
vtex-sites/storecomponents.store pull request #978
Opened 2021-06-14 22:39 UTC by felippenardi

## What's the purpose of this pull request?
Add preview capability to the homepage.

## How it works? 
It renders the `Above` and `Below` the fold by passing a combination of a mock content and the runtime-fetched CMS content for the specified variant.

It then keeps polling CMS for updates as a way to automatically update when users save changes in the CMS. This is not a performance problem because we are not concerned about performance in the preview.

## How to test it?
Run `yarn run development`
Open http://localhost:8000/preview?contentVariantId=64d34c01-39d8-4776-9885-4da0a71efb73

This should render a preview of a specific variant of the Homepage content.

2021-06-15 18:01 UTC, felippenardi commented on src/pages/preview.tsx
> +  'https://nardi88--storecomponents.myvtex.com/_v/admin-cms-graphql-rc/v0/contentVariant?variantId='
This will be replaced for production before this is merged

2021-06-15 19:16 UTC, tlgimenes commented on src/pages/preview.tsx
> +const CMS_BASE_URL =
you can use something like: `/cms` and `createRedirect` on `gatsby-plugin-cms`

2021-06-17 14:06 UTC, felippenardi commented on src/pages/preview.tsx
> +const CMS_BASE_URL =
But wouldn’t it be different for every account?

2021-06-17 14:11 UTC, tlgimenes commented on src/pages/preview.tsx
> +const CMS_BASE_URL =
yes. We do this for our /graphql for instance. Take a look at: https://github.com/vtex/faststore/blob/cf6c2af5042d685e86fddb6f31b6287d6cf6b64d/packages/gatsby-source-vtex/src/gatsby-node.ts#L378

2021-06-17 16:38 UTC, emersonlaurentino reviewed
Do we need the mock?

2021-06-18 19:10 UTC, emersonlaurentino approved these changes

2021-06-18 19:13 UTC, tlgimenes requested changes

2021-06-18 19:13 UTC, tlgimenes commented on src/pages/preview.tsx
> +const MOCK = {
Why mocking products? It's a bad since if we change the graphql query, we need to mock the other graphql data in here as well. I'd prefer being able to fetch the data with the same shape as the graphql in index.

2021-06-18 19:14 UTC, tlgimenes commented on src/pages/preview.tsx
> +import React, { useRef, useEffect } from 'react'
please take a look at the sonarqube

2021-06-18 19:15 UTC, tlgimenes reviewed
The thing I still don't know is how to do this preview for the search page like in /apparel---accessories

2021-06-18 19:52 UTC, felippenardi commented on src/pages/preview.tsx
> +const MOCK = {
How can we make this query at runtime?
https://github.com/vtex-sites/storecomponents.store/blob/master/src/%40vtex/gatsby-theme-store/pages/index.tsx#L10-L43

2021-06-18 19:59 UTC, felippenardi commented
@tlgimenes We want to provide the user a way to quickly preview what they are building on the CMS. This is not a high fidelity preview—it is a preview of just the thing they can edit on the CMS itself.

It is ok for the home page products to be different or use a greyed out version of products, eventually making it explicit that we are not loading this information at the preview for example.

So the search page could look somewhat similar: the facets are going to be static and the search result would show greyed-out products that makes it clear that this content is not being rendered in the preview.

2021-06-18 20:03 UTC, tlgimenes commented
> So the search page could look somewhat similar: the facets are going to be static and the search result would show greyed-out products that makes it clear that this content is not being rendered in the preview.

Nice! I think it would be great to show a poc with this. Can you include it in here?

2021-06-18 20:03 UTC, tlgimenes commented on src/pages/preview.tsx
> +const MOCK = {
That's my question, I have no ideia, ahha

2021-06-24 18:14 UTC, tlgimenes commented on src/pages/preview.tsx
> +    <Layout>
<Page />

2022-01-24 15:15 UTC, closed without merging